require('Melal.plugins-setup')
require('Melal.core.colorscheme')
require('Melal.core.options')
require('Melal.core.keymaps')
require('Melal.plugins.comment')
require('Melal.plugins.nvim-tree')
require('Melal.plugins.telescope')
require('Melal.plugins.nvim-cmp')
--require('Melal.plugins.lualine')

